<?php

return [
    'Nebula Drifter',
    'Quantum Voyager',
    'Starlight Nomad',
    'Celestial Serpent',
    'Solar Wanderer',
    'Galactic Mirage',
    'Cosmic Falcon',
    'Nebula Phoenix',
    'Hypernova Explorer',
    'Astro Nomad',
    'Celestial Seeker',
    'Lunar Marauder',
    'Starstruck Dreamer',
    'Void Runner',
    'Orbit Vindicator',
    'Nova Ghost',
    'Sky Raider',
    'Pulsar Rider',
    'Photon Drifter',
    'Astral Nomad',
    'Solar Rogue',
    'Quasar Whisper',
    'Intergalactic Mirage',
    'Nebula Wraith',
    'Gravity Phantom',
    'Stellar Pirate',
    'Comet Streaker',
    'Nebula Zephyr',
    'Celestial Breeze',
    'Event Horizon',
];
